// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADjhLClEuraJpGt9XQsInzablCx7OtaRA',
    appId: '1:769543387371:web:80d0cd1b0e4f8c86f2a6ae',
    messagingSenderId: '769543387371',
    projectId: 'system-audit-62b5f',
    authDomain: 'system-audit-62b5f.firebaseapp.com',
    storageBucket: 'system-audit-62b5f.firebasestorage.app',
    measurementId: 'G-EDHFLPKR66',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDo07pZPq3gKLlNTlQqAJJPr1vtOe3_LCE',
    appId: '1:769543387371:android:20af637ee0f31cf7f2a6ae',
    messagingSenderId: '769543387371',
    projectId: 'system-audit-62b5f',
    storageBucket: 'system-audit-62b5f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2CRW752jsAux1DiCuxUryEBZJ_WL8Sws',
    appId: '1:769543387371:ios:a18e5a577ca68a48f2a6ae',
    messagingSenderId: '769543387371',
    projectId: 'system-audit-62b5f',
    storageBucket: 'system-audit-62b5f.firebasestorage.app',
    iosBundleId: 'com.example.skillsAuditMobile',
  );
}
